<?php

/**
 * Vnext Software.
 *
 * @category  Mpx
 * @package   Mpx_Backend
 * @author    Mpx
 */

use Magento\Backend\Block\Page\Copyright;

// @codingStandardsIgnoreFile
/**
 * @var $block Copyright
 */
?>

<a class="logo-mpx-footer" title="<?= $block->escapeHtmlAttr(__('X SHOPPING STREET')) ?>"></a>
<br>
<a class="link-report" href="#" id="footer_privacy" target="_blank">
    <?= $block->escapeHtml(__('Terms Of Service')) ?>
</a>

<a class="link-report" href="#" id="footer_privacy" target="_blank">
    <?= $block->escapeHtml(__('Privacy Policy')) ?>
</a>

<a class="link-report" href="#" id="footer_privacy" target="_blank">
    <?= $block->escapeHtml(__('Inquiry')) ?>
</a>

<a class="link-account-activity"
   href="<?= $block->escapeUrl($block->getUrl('security/session/activity')) ?>"
   id="footer_account_activity"
   target="_blank"
   data-mage-init='{"popupWindow": {
        "windowURL": "<?= $block->escapeJs($block->escapeUrl($block->getUrl('security/session/activity'))) ?>",
        "windowName": "session-activity",
        "width": 600, "height": 600, "top": 50, "left": 50, "resizable": 1, "scrollbars": 1}}'>
    <?= $block->escapeHtml(__('Account Activity')) ?>
</a>
<br>
<a id="footer-text-admin">
    <?= $block->escapeHtml(__('© 2022 TRUE Inc.', date('Y'))) ?>
</a>