<?php
/**
 * Mpx Software.
 *
 * @category  Mpx
 * @package   Mpx_Marketplace
 * @author    Mpx
 */
$helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$partner=$block->getProfileDetail();
if ($partner['shop_url']) {
    if ($helper->getActiveColorPicker()) { ?>
        <style>
            .page-main{
                background-image:none;
                background-color:<?= $block->escapeHtml($partner['background_width']);?>;
            }
        </style>
    <?php } ?>
    <div class="wk_mp_design">
        <?= $block->getChildHtml("marketplace_seller_top_block")?>
        <div class="wk-mp-collection-container">
            <?= $this->getChildHtml('marketplace_sellerprofile_recently_added_products')?>
            <div class="wk-mp-profile-block" id="about-us">
                <div class="wk-mp-aboutus-title">
                    <?= $block->escapeHtml(__("About Us"))?>
                </div>
                <div class="wk-mp-aboutus-data">
                    <?= /* @noEscape */ $partner['company_description'];?>
                    <?= $block->getChildHtml("marketplace_seller_description")?>
                </div>
            </div>
            <?= $this->getChildHtml('marketplace_sellerprofile_rating')?>
            <?php if ($helper->getSellerPolicyApproval()) { ?>
                <div class="wk-mp-profile-block" id="wk-mp-policy-block">
                    <div class="wk-mp-policy-block wk-mp-shipping-policy" id="shipping-policy">
                        <div class="wk-mp-policy-block-title">
                            <?= $block->escapeHtml(__("Regarding delivery"))?>
                        </div>
                        <div class="wk-mp-policy-block-data"><?= /* @noEscape */ $partner['shipping_policy'];?></div>
                    </div>
                    <div class="wk-mp-policy-block wk-mp-return-policy" id="return-policy">
                        <div class="wk-mp-policy-block-title">
                            <?= /* @noEscape */ __("Cancellation/return")?>
                        </div>
                        <div class="wk-mp-policy-block-data"><?= /* @noEscape */ $partner['return_policy'];?></div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
<?php }  ?>
