<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Gallery\Content */
$elementNameEscaped = $block->escapeHtmlAttr($block->getElement()->getName()) . '[images]';
$formNameEscaped = $block->escapeHtmlAttr($block->getFormName());
?>

<div class="row">
    <div class="add-video-button-container">
        <button disabled id="add_video_button"
                title="<?= $block->escapeHtmlAttr(__('Add Video')) ?>"
                data-role="add-video-button"
                type="button"
                class="action-secondary"
                data-ui-id="widget-button-1">
            <span><?= $block->escapeHtml(__('Add Video')) ?></span>
        </button>
    </div>
</div>

<?php
/** @var $block \Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Gallery\Content */
$element = $block->getElement();
$elementToggleCode = $element->getToggleCode() ? $element->getToggleCode() : 'toggleValueElements(this, this.parentNode.parentNode.parentNode)';
?>
<div id="<?= /* @noEscape */ $block->getHtmlId() ?>"
     class="gallery"
     data-mage-init='{"openVideoModal":{}}'
     data-parent-component="<?= $block->escapeHtmlAttr($block->getData('config/parentComponent')) ?>"
     data-images="<?= $block->escapeHtmlAttr($block->getImagesJson()) ?>"
     data-types='<?= /* @noEscape */ $this->helper(Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getImageTypes()) ?>'
>
    <?php if (!$block->getElement()->getReadonly()) : ?>
        <?= $block->getChildHtml('additional_buttons') ?>
    <?php endif; ?>
    <?php foreach ($block->getImageTypes() as $typeData) : ?>
        <input name="<?= $block->escapeHtmlAttr($typeData['name']) ?>"
               data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"
               class="image-<?= $block->escapeHtmlAttr($typeData['code']) ?>"
               type="hidden"
               value="<?= $block->escapeHtmlAttr($typeData['value']) ?>"/>
    <?php endforeach; ?>
    <script id="<?= /* @noEscape */ $block->getHtmlId() ?>-template" data-template="image" type="text/x-magento-template">
        <div class="image item <% if (data.disabled == 1) { %>hidden-for-front<% } %>  <% if (data.video_url) { %>video-item<% } %>"
             data-role="image">
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][position]"
                   value="<%- data.position %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"
                   class="position"/>
            <% if (data.media_type !== 'external-video') {%>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][media_type]"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"
                   value="image"/>
            <% } else { %>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][media_type]"
                   value="<%- data.media_type %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>
            <% } %>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][video_provider]"
                   value="<%- data.video_provider %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][file]"
                   value="<%- data.file %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][value_id]"
                   value="<%- data.value_id %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][label]"
                   value="<%- data.label %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][disabled]"
                   value="<%- data.disabled %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][removed]"
                   value="" class="is-removed"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][video_url]"
                   value="<%- data.video_url %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][video_title]"
                   value="<%- data.video_title %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][video_description]"
                   value="<%- data.video_description %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][video_metadata]"
                   value="<%- data.video_metadata %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape */ $elementNameEscaped ?>[<%- data.file_id %>][role]"
                   value="<%- data.video_description %>"
                   data-form-part="<?= /* @noEscape */ $formNameEscaped ?>"/>

            <div class="product-image-wrapper">
                <img class="product-image"
                     data-role="image-element"
                     src="<%- data.url %>"
                     alt="<%- data.label %>"/>

                <div class="image-fade"><span><?= $block->escapeHtml(__('Hidden')); ?></span></div>
            </div>

            <div class="item-description">
                <% if (data.media_type !== 'external-video') {%>
                <div class="item-title" data-role="img-title"><%- data.label %></div>
                <div class="item-size">
                    <span data-role="image-dimens"></span>, <span data-role="image-size"><%- data.sizeLabel %></span>
                </div>
                <% } else { %>
                <div class="item-title" data-role="img-title"><%- data.video_title %></div>
                <% } %>
            </div>

            <ul class="item-roles" data-role="roles-labels">
                <?php foreach ($block->getImageTypes() as $typeData) : ?>
                    <li data-role-code="<?= $block->escapeHtmlAttr($typeData['code']) ?>" class="item-role item-role-<?= $block->escapeHtmlAttr($typeData['code']) ?>">
                        <?= $block->escapeHtml($typeData['label']) ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </script>

    <div id="<?= /* @noEscape */ $block->getNewVideoBlockName() ?>" style="display:none">
        <?= $block->getFormHtml() ?>
        <div id="video-player-preview-location" class="video-player-sidebar">
            <div class="video-player-container"></div>
            <div class="video-information title">
                <label><?= $block->escapeHtml(__('Title:')); ?> </label><span></span>
            </div>
            <div class="video-information uploaded">
                <label><?= $block->escapeHtml(__('Uploaded:')); ?> </label><span></span>
            </div>
            <div class="video-information uploader">
                <label><?= $block->escapeHtml(__('Uploader:')); ?> </label><span></span>
            </div>
            <div class="video-information duration">
                <label><?= $block->escapeHtml(__('Duration:')); ?> </label><span></span>
            </div>
        </div>
    </div>

    <?= $block->getChildHtml('new-video') ?>
</div>
<script>
    jQuery('body').trigger('contentUpdated');
</script>
