<?php

$helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$orderHelper = $this->helper(\Webkul\Marketplace\Helper\Orders::class);
$isPartner = $helper->isSeller();
$trackingCode = $block->_customerSession->getTrackingCode();
$customSelectedFlag = false;
if (!$trackingCode) {
    $trackingCode = $block->getDefaultCarrierCode();
}
$trackingTitle = $block->_customerSession->getTrackingTitle();
if (!$trackingTitle) {
    $trackingTitle = $block->getDefaultCarrierTitle();
}
if ($isPartner == 1) {
    $orderId = $this->getRequest()->getParam('order_id');
    $shipmentId = $this->getRequest()->getParam('shipment_id');
    $order = $block->getOrder();
    $tracking = $orderHelper->getOrderinfo($orderId);

    $paymentMethod = '';
    if ($order->getPayment()) {
        $paymentMethod = $order->getPayment()->getMethodInstance()->getTitle();
    }
    $marketplaceOrders = $block->getSellerOrderInfo($orderId);
    if (count($marketplaceOrders)) {    ?>
    <form data-mage-init='{"validation": {}}' action="<?= $block->escapeUrl($block->getUrl('mpx/order/shipment', ['order_id'=>$orderId, '_secure' => $this->getRequest()->isSecure()]))?>" name="forma" id="mpx-shipping-form-1" method="post">
        <div class="wk-mp-design">
            <div class="fieldset wk-mp-fieldset">
                <div class="page-title-wrapper">

                    <div class="actions-toolbar order-actions-toolbar">
                        <div class="actions">
                            <a href="<?= $block->escapeUrl($block->getUrl('mpx/order/shipment', ['order_id'=>$orderId, '_secure' => $this->getRequest()->isSecure()]));?>" class="action">
                                <button  class="button wk-mp-btn" id="wk-mp-btn-shipment"  title="<?= /* @noEscape */ __('Submit Shipment') ?>">
                                    <span><span><?= /* @noEscape */ __('Submit Shipment') ?></span></span>
                                </button>
                            </a>
                            <button onclick="window.history.go(-1); return false;" id="back_history" class="button wk-mp-btn" title="<?= /* @noEscape */ __('Back') ?>">
                                <span><span><?= /* @noEscape */ __('Back') ?></span></span>
                            </button>

                            <?php
                            foreach ($block->getChildNames() as $key => $blockName) {
                                if ($blockName != 'mpx_marketplace_order_items') {
                                    echo $block->getChildHtml($blockName, false);
                                }
                            } ?>
                        </div>
                    </div>
                </div>
                <div class="block block-order-details-view">
                    <div class="block-title">
                        <strong><?= /* @noEscape */ __('Order Information') ?></strong>
                    </div>
                    <div class="block-content">
                        <div class="box-content">
                            <div class="box wk-box">
                                <strong class="box-title wk-order-info-title">
                                    <a href="<?= $block->escapeUrl($block->getUrl('marketplace/order/view', ['id'=>$orderId, '_secure' => $this->getRequest()->isSecure()]));?>">
                                        <?= /* @noEscape */ __('Order # %1', $order->getIncrementId()) ?>
                                    </a>
                                </strong>
                                <div class="box-content">
                                    <div class="wk-row">
                                        <span class="label"><?= /* @noEscape */ __('Order Status')?> : </span>
                                        <span class="value"><?= $block->escapeHtml(ucfirst($order->getStatus())); ?></span>
                                    </div>
                                    <div class="wk-row">
                                        <span class="label"><?= /* @noEscape */ __('Order Date')?> : </span>
                                        <span class="value"><?=/* @noEscape */ $block->formatDate($order->getCreatedAt(), \IntlDateFormatter::MEDIUM, true, $block->getTimezoneForStore($order->getStore())); ?></span>
                                    </div>
                                </div>
                            </div>
                            <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                                <div class="box wk-box">
                                    <strong class="box-title"><span><?= /* @noEscape */ __('Buyer Information') ?></span></strong>
                                    <div class="box-content">
                                        <div class="box wk-box">
                                            <div class="wk-row">
                                                <span class="label"><?= /* @noEscape */ __('Customer Name')?> : </span>
                                                <span class="value"><?= $block->escapeHtml($order->getCustomerName()); ?></span>
                                            </div>
                                            <div class="wk-row">
                                                <span class="label"><?= /* @noEscape */ __('Email')?> : </span>
                                                <span class="value"><?= $block->escapeHtml($order->getCustomerEmail()); ?></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                    <div class="block block-order-details-view">
                        <div class="block-title">
                            <strong><?= /* @noEscape */ __('Address Information') ?></strong>
                        </div>
                        <div class="block-content">
                            <div class="box-content">
                                <div class="box box-order-billing-address wk-box">
                                    <strong class="box-title">
                                        <span><?= /* @noEscape */ __('Billing Address') ?></span>
                                    </strong>
                                    <div class="box-content">
                                        <address><?= /* @noEscape */ $block->getFormattedAddress($order->getBillingAddress()); ?></address>
                                    </div>
                                </div>
                                <?php if (!$order->getIsVirtual()): ?>
                                    <div class="box box-order-shipping-address wk-box">
                                        <strong class="box-title"><span><?= /* @noEscape */ __('Shipping Address') ?></span></strong>
                                        <div class="box-content">
                                            <address><?= /* @noEscape */ $block->getFormattedAddress($order->getShippingAddress()); ?></address>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <div class="block block-order-details-view">
                    <div class="block-title">
                        <strong><?= /* @noEscape */ __('Payment & Shipping Method') ?></strong>
                    </div>
                    <div class="block-content">
                        <div class="box box-order-billing-method wk-box">
                            <strong class="box-title">
                                <span><?= /* @noEscape */ __('Payment Information') ?></span>
                            </strong>
                            <div class="box-content">
                                <?= $block->escapeHtml($paymentMethod); ?>
                            </div>
                        </div>
                        <?php if (!$order->getIsVirtual()): ?>
                            <div class="box box-order-shipping-method wk-box">
                                <strong class="box-title">
                                    <span><?= /* @noEscape */ __('Shipping and Tracking Information') ?></span>
                                </strong>
                                <div class="box-content">
                                    <?php if ($order->getShippingDescription()): ?>
                                        <?= $block->escapeHtml($order->getShippingDescription()) ?>
                                    <?php else: ?>
                                        <?= /* @noEscape */ __('No shipping information available'); ?>
                                    <?php endif; ?>

                                    <p>
                                        <a href="<?= $block->escapeUrl($this->helper(\Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($block->getShipment())) ?>" title="<?= /* @noEscape */ __('Track this shipment') ?>" target="blank">
                                            <?= /* @noEscape */ __('Track this shipment') ?>
                                        </a>
                                    </p>
                                    <div class="admin__control-table-wrapper">
                                        <table class="data-table admin__control-table wk-mp-list-table" id="wk-mp-shipment-tracking-info">
                                            <thead>
                                            <tr class="headings">
                                                <th><?= /* @noEscape */ __('Carrier') ?></th>
                                                <th><?= /* @noEscape */ __('') ?></th>
                                                <th><?= /* @noEscape */ __('Number') ?></th>

                                            </tr>
                                            </thead>
                                            <tfoot>
                                            <tr>
                                                <td>
                                                    <select name="carrier"
                                                            class="select"
                                                            id="wk-mp-tracking-carrier">
                                                         <?php foreach ($block->getCarriers() as $_code => $_name): ?>
                                                            <?php if ($trackingCode == $_code): ?>
                                                                 <?php if ($_code == 'custom') {
                                                                     $customSelectedFlag = true;
                                                                 }
                                                                 ?>
                                                                <option selected value="<?= $block->escapeHtml($_code) ?>">
                                                                    <?= $block->escapeHtml($_name) ?>
                                                                </option>
                                                            <?php else : ?>
                                                                <option value="<?= $block->escapeHtml($_code) ?>">
                                                                    <?= $block->escapeHtml($_name) ?>
                                                                </option>
                                                            <?php endif  ?>
                                                        <?php endforeach; ?>
                                                    </select>
                                                </td>
                                                <td>
                                                    <input class="input-text required"
                                                           type="text"
                                                           id="wk-mp-tracking-title"
                                                           name="title"
                                                           value="<?= $trackingTitle ?>"
                                                            <?php echo (!$customSelectedFlag) ? 'style="display:none;"' : ''; ?>
                                                    />
                                                </td>
                                                <td >
                                                    <input class="input-text required"
                                                           type="text"
                                                           id="wk-mp-tracking-number"
                                                           name="number"
                                                           value="" />
                                                </td>
                                            </tr>
                                            </tfoot>

                                        </table>
                                    </div>

                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="block block-order-details-view wk-order-title-block">
                    <div class="block-title">
                        <strong><?= /* @noEscape */ __('Items Shipped') ?></strong>
                    </div>
                </div>
                <div class="order-details-items ordered">
                    <div class="order-title">
                        <strong><?= /* @noEscape */ __('Items Shipped') ?></strong>
                    </div>
                    <?= $block->getChildHtml('mpx_marketplace_order_items') ?>
                </div>
                <section class="shipping-total-additional">
                    <div class="block block-shipping-total wk-order-title-block">
                        <div class="block-title">
                            <strong><?= /* @noEscape */ __('Shipment Total') ?></strong>
                        </div>
                    </div>
                    <div id="shipment-comment" class="shipment-comment-content order-comments-history">
                        <div class="shipment-comment">
                            <div class="shipment-comment-title">
                                <strong class="title"><?= $block->escapeHtml(__('Shipment Comments')) ?></strong>
                            </div>
                            <div class="shipment-comment-content">
                                <div id="order-history_form" class="admin__field">
                                    <label class="admin__field-label"
                                           for="shipment_comment_text">
                                        <span><?= $block->escapeHtml(__('Comment Text')) ?></span></label>
                                    <div class="shipment-comment-field-control">
                        <textarea id="shipment_comment_text"
                                  class="admin__control-textarea"
                                  name="shipment[comment_text]"
                                  rows="3"
                                  cols="5"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="shipment-email" class="shipment-email-content-section-item order-totals order-totals-actions">
                        <div class="shipment-email-content-section-item-title">
                            <strong class="title"><?= $block->escapeHtml(__('Shipment Options')) ?></strong>
                        </div>
                        <div class="shipment-email-content-section-item-content">
                            <div class="field choice shipment-comment-content__field shipment-email-content__field-option field-create">
                                <input id="create_shipping_label"
                                       class="shipment-email-checkbox"
                                       name="shipment[create_shipping_label]"
                                       value="1"
                                       type="checkbox"
                                       onclick=""/>
                                <label class="shipment-email-label"
                                       for="create_shipping_label">
                                    <span><?= $block->escapeHtml(__('Create Shipping Label')) ?></span></label>
                            </div>
                            <div class="field choice shipment-email shipment-email-option field-append">
                                <input id="notify_customer"
                                       class="shipment-email-checkbox"
                                       name="shipment[comment_customer_notify]"
                                       value="1"
                                       type="checkbox"/>
                                <label class="shipment-email-label"
                                       for="notify_customer">
                                    <span><?=$block->escapeHtml(__('Append Comments')) ?></span></label>
                            </div>

                            <div class="field choice shipment-email shipment-email-option field-email">
                                <input id="send_email"
                                       class="shipment-email-checkbox"
                                       name="shipment[send_email]"
                                       value="1"
                                       type="checkbox" checked/>
                                <label class="shipment-email-label"
                                       for="send_email">
                                    <span><?= $block->escapeHtml(__('Send a delivery notification email')) ?></span></label>
                            </div>
                            <?= $block->getChildHtml('submit_before') ?>
                            <div class="order-history-comments-actions actions">
                                <?= $block->getChildHtml('submit_button') ?>
                                <?= $block->getChildHtml('submit_after') ?>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>

</form>
        <div class="buttons-set">
            <p class="back-link">
                <a href="<?= $block->escapeUrl($block->getUrl('marketplace/order/history', ['_secure' => $this->getRequest()->isSecure()]));?>" class="left">&laquo; <?= /* @noEscape */ __('Back To My Orders') ?></a>
            </p>
        </div>
        <script>
            require([
                "jquery",
                "mage/mage"
            ], function($) {
                var dataForm = $('#mpx-shipping-form-1');
                dataForm.mage('validation', {});

                $('#mp-create-shipment-btn').click(function() {
                    dataForm.submit();
                });

                $('form').submit(function() {
                    if (dataForm.valid()) {
                        $(this).find("button[id='wk-mp-btn-shipment']").prop('disabled', true);
                    }
                });
            });
            $('#back_history').click(function() {
                var confimation = confirm('<?= /* @noEscape */ __("Are you sure you want to create shipment?") ?>');
                if (confimation) {
                    dataForm.submit();
                }
            });
        </script>
        <script id="sellerOrderShipmentTemplate" type="text/x-jquery-tmpl">
            <tr>
                <td><%- data.carrier %></td>
                <td><%- data.title %></td>
                <td class="<%- data.numberclass %>">
                    <%- data.number %>
                </td>
                <td class="<%- data.numberclasshref %>">
                    <a href="<%- data.trackingPopupUrl %>" target="blank">
                        <%- data.number %>
                    </a>
                </td>
                <td class="col-delete">
                    <button class="wk-mp-tracking-action-delete action-delete" data-url="<%- data.trackingDeleteUrl %>">
                        <span>
                            <?= /* @noEscape */ __('Delete') ?>
                        </span>
                    </button>
                </td>
            </tr>
        </script>
        <?php
        $formData = [
            'addTrackingAjaxUrl' => $block->trackingAddUrl($orderId, $shipmentId)
        ];
        $serializedFormData = $this->helper(
            \Magento\Framework\Json\Helper\Data::class
        )->jsonEncode($formData);
        ?>
        <script type="text/x-magento-init">
            {
                "*": {
                    "sellerOrderShipment": <?= /* @noEscape */ $serializedFormData; ?>
                }
            }
        </script>
        <?php
    }
} else { ?>
    <h2 class="wk-mp-error_msg">
        <?= /* @noEscape */ __("To Become Seller Please Contact to Admin."); ?>
    </h2>
    <?php
} ?>
