<?php
/**
 * Webkul Software
 *
 * @category Webkul
 * @package Webkul_MpTimeDelivery
 * @author Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */
$_item = $block->getItem();
$_order = $_item->getOrder();
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $block->escapeHtml(__('SKU')); ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <dl class="item-options">
            <?php if ($_item->getDeliveryDate()!=''): ?>
            <dt><strong><em><?= $block->escapeHtml(__('Delivery Date/Day: ')) ?></em></strong></dt>
            <dd><span><?= $block->escapeHtml($_item->getDeliveryDate()) ?></span></dd>
            <dt><strong><em><?= $block->escapeHtml(__('Delivery Time: ')) ?></em></strong></dt>
            <dd><span><?= $block->escapeHtml($_item->getDeliveryTime()) ?></span></dd>
            <?php endif; ?>
        </dl>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                <dd>
                    <?= /* @escapeNotVerified */  $block->escapeHtml(nl2br($option['value'])) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock):?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= $block->escapeHtml($_item->getQtyOrdered()) * 1 ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $block->getItemPrice($_item); ?>
    </td>
</tr>
<?php
$_giftMessage = $block->getData('timeSlotHelper')->getGiftMessageObject()->getGiftMessage($_item->getGiftMessageId());
if ($_item->getGiftMessageId() && $_giftMessage): ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= $block->escapeHtml(__('Gift Message')) ?></h3>
                    <strong>
                        <?= $block->escapeHtml(__('From:')); ?>
                    </strong> 
                    <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br />
                    <strong>
                        <?= $block->escapeHtml(__('To:')); ?>
                    </strong> 
                        <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br />
                    <strong>
                        <?= $block->escapeHtml(__('Message:')); ?>
                    </strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
