<?php
// @codingStandardsIgnoreFile
/**
 * Mpx Software.
 *
 * @category  Mpx
 * @package   Mpx_Marketplace
 * @author    Mpx
 */
/** @var $block \Webkul\Marketplace\Block\Account\Dashboard */

$helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$captchaEnableStatus = $helper->getCaptchaEnable();
$getDateDetail = $block->getDateDetail();
$totalSaleColl = $block->getTotalSaleColl();
$totalSale = 0;
$totalRemainSale = 0;
foreach ($totalSaleColl as $value) {
    $totalSale = $value->getAmountReceived();
    $totalRemainSale = $value->getAmountRemain();
}
$totalSaleK = $totalSale / 1000;
if ((int)$totalSaleK) {
    $totalSaleToDisplay = $totalSaleK;
    $totalSaleType = "K";
} else {
    $totalSaleToDisplay = $totalSale;
    $totalSaleType = "";
}
$totalLifeTimeSale = $totalSale+$totalRemainSale;
$totalLifeTimeSaleK = $totalLifeTimeSale / 1000;
if ((int)$totalLifeTimeSaleK) {
    $totalLifeTimeSaleToDisplay = $totalLifeTimeSaleK;
    $totalLifeTimeSaleType = "K";
} else {
    $totalLifeTimeSaleToDisplay = $totalLifeTimeSale;
    $totalLifeTimeSaleType = "";
}
?>
<div class="wk-mp-design">
    <div class="wk-mp-dashboard-main-container">
        <div class="wk-mp-dashboard-main-column">
            <?= $block->getChildHtml('marketplace_dashboard_totals')?>
        </div>
    </div>
    <?= $block->getChildHtml('dashboard_additional_content_block')?>
    <?= $this->getChildHtml('marketplace_dashboard_latest_orders')?>
</div>
<?php if ($helper->getSellerProfileDisplayFlag()) { ?>
    <?= $this->getChildHtml('marketplace_dashboard_customer_review')?>
<?php } ?>
<div class="ask-que">
    <div id="wk-mp-ask-data">
        <div class="wk-mp-modals-wrapper">
            <aside tabindex="0" data-type="popup" data-role="modal" class="modal-popup modal-slide _inner-scroll wk-mp-model-popup">
                <div tabindex="0" data-role="focusable-start"></div>
                <div data-role="focusable-scope" class="modal-inner-wrap">
                    <header class="modal-header">
                        <h4 class="modal-title"><?= /* @noEscape */ __('Ask Question to Admin') ?></h4>
                        <button type="button" data-role="closeBtn" class="action-close wk-close">
                            <span>Close</span>
                        </button>
                        <span  class="wk-clear" ></span>
                    </header>
                    <form id="ask-form" method="post" action="#" class="fieldset" data-role="ask-form" data-mage-init='{"validation":{}}'>
                        <div class="modal-body form-list field required">
                            <label class="label"><?= /* @noEscape */ __('Subject') ?> :</label>
                            <input type="text" name="subject" class="wk-contact_input_fields required-entry"/>
                            <label class="label"><?= /* @noEscape */ __('Your Query') ?> :</label>
                            <textarea  name="ask" class="queryquestion wk-contact_input_fields required-entry" style="width:100%;"></textarea>
                            <input type="hidden" name="seller-id" value="<?= /* @noEscape */ $block->getCustomerId();?>"/>
                            <?php
                            if ($captchaEnableStatus) {?>
                                <div>
                                    <span>
                                        <label for="wk-mp-captcha"><span id="wk-mp-captchalable1"><?= /* @noEscape */ rand(1, 20)?></span> + <span id="wk-mp-captchalable2"><?= /* @noEscape */ rand(1, 20)?></span> =</label>
                                    </span>
                                    <input type="text" class="required-entry wk-contact_input_fields" name="wk-mp-captcha" id="wk-mp-captcha" />
                                </div>
                                <?php
                            }?>
                        </div>
                        <div class="modal-footer">
                            <span class="error"></span>
                            <span class="errormail"></span>
                            <input type="reset" value="<?= /* @noEscape */ __('Reset') ?>" id="resetbtn" class="wk-btn wk-btn_default"/>
                            <input type="submit" value="<?= /* @noEscape */ __('Submit') ?>" id="askbtn" class="wk-btn wk-btn-primary clickask"/>
                            <span class="wk-clear"></span>
                        </div>
                    </form>
                </div>
                <div tabindex="0" data-role="focusable-end"></div>
            </aside>
        </div>
    </div>
</div>
<?php
$formData = [
    'loader'                =>$this->getViewFileUrl('images/loader-2.gif'),
    'mpLocationChartSelector' => '#wk-location-chart',
    'mpYearLocationChartSelector' => '#wk-location-chart-year',
    'mpAskDataSelector'     => '#wk-mp-ask-data',
    'askQueSelector'        => '#askque',
    'askFormSelector'       => '#ask-form',
    'askFormInputSelector'  => '#ask-form input',
    'askFormTextareaSelector' =>'#ask-form textarea',
    'pageWrapperSelector'   => '.wk-mp-page-wrapper',
    'mpModelPopupSelector'  => '.wk-mp-model-popup',
    'showClass'             => '_show',
    'mageErrorClass'        => 'mage-error',
    'resetBtnSelector' => '#resetbtn',
    'wkCloseSelector' => '.wk-close',
    'validationFailedSelector' => '.validation-failed',
    'askFormValidationFailedSelector'   =>  '#ask-form .validation-failed',
    'askFormValidationAdviceSelector'   =>  '#ask-form .validation-advice',
    'askFormErrorMailSelector'      => '#ask-form .errormail',
    'askBtnSelector'        =>  '#askbtn',
    'mpCaptcha1Selector'    =>  '#wk-mp-captchalable1',
    'mpCaptcha2Selector'    =>  '#wk-mp-captchalable2',
    'mpCaptchaSelector'     =>  '#wk-mp-captcha',
    'mailProcssClass'       =>  'mail-procss',
    'captchaEnableStatus'   =>  $captchaEnableStatus,
    'ajaxMailSendUrl'       =>  $block->getUrl("marketplace/account/askquestion", ["_secure" => $this->getRequest()->isSecure()]),
    'ajaxChartUrl'          =>  $block->getUrl("marketplace/account/chart", ["_secure" => $this->getRequest()->isSecure()])
];
$serializedFormData = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "sellerDashboard": <?= /* @noEscape */ $serializedFormData; ?>
        }
    }
</script>
